### ISSUE TITLE
Can not run modpack on pop os 20.04

### ISSUE THREAD

**Issue by Lapatou** [CreeperHost/modpacklauncher#18]
I install ftb launcher and download FTB University and FTB Revelation but bolt of them does not run or show error

**Comment by gigabit101** [comment]
We will need your latest log file to look into the issue

**Comment by Lapatou** [comment]
[https://www.dosya.tc/server32/5wbqnd/launcher.log.html](url) here you can download

**Comment by Lapatou** [comment]
http://www.mediafire.com/file/564sa56k9e4pwkh/launcher.log/file here you can download launcher.log file in FTBA folder

**Comment by www2000** [comment]
I have the same problem I know that the problem with ubuntu 20.04 and 20.10.
The problem is that FTB have no (easy to access) option forsing minecraft to use a spesific java/openjdk version (for me is opendjk 8) nor minecraft can't remember the java version setting in the minecraft launcher.
Current work arround that i have is evertime that i launch minecraft i reset the java path to this: /usr/lib/jvm/java-8-openjdk-amd64/bin/java

**Comment by gigabit101** [comment]
You should now be able to set the JRE in the instance settings via the FTBApp
